name: OneShot

options:
  bundleIdPrefix: com.grantbirki
  deploymentTarget:
    macOS: "14.0"

targets:
  OneShot:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Sources/Resources/shutter.wav
      - Sources/Resources/Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: OneShot
        CFBundleIconName: AppIcon
        GIT_SHA: $(GIT_SHA)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSScreenCaptureUsageDescription: OneShot needs screen recording access to capture screenshots.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grantbirki.oneshot
        MARKETING_VERSION: 0.0.0
        CURRENT_PROJECT_VERSION: 0.0.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  OneShotTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: OneShot
