enum SettingsStoreKeys {
    static let autoLaunchEnabled = "settings.autoLaunchEnabled"
    static let menuBarIconHidden = "settings.menuBarIconHidden"
    static let showSelectionCoordinates = "settings.showSelectionCoordinates"
    static let saveDelaySeconds = "settings.saveDelaySeconds"
    static let previewTimeoutEnabled = "settings.previewTimeoutEnabled"
    static let previewEnabled = "settings.previewEnabled"
    static let previewAutoDismissBehavior = "settings.previewAutoDismissBehavior"
    static let previewReplacementBehavior = "settings.previewReplacementBehavior"
    static let previewDisabledOutputBehavior = "settings.previewDisabledOutputBehavior"
    static let selectionDimmingMode = "settings.selectionDimmingMode"
    static let selectionDimmingColorHex = "settings.selectionDimmingColorHex"
    static let selectionVisualCue = "settings.selectionVisualCue"
    static let autoCopyToClipboard = "settings.autoCopyToClipboard"
    static let saveLocationOption = "settings.saveLocationOption"
    static let customSavePath = "settings.customSavePath"
    static let filenamePrefix = "settings.filenamePrefix"
    static let shutterSoundEnabled = "settings.shutterSoundEnabled"
    static let shutterSound = "settings.shutterSound"
    static let shutterSoundVolume = "settings.shutterSoundVolume"
    static let hotkeySelectionKeyCode = "settings.hotkeySelection.keyCode"
    static let hotkeySelectionModifiers = "settings.hotkeySelection.modifiers"
    static let hotkeyFullScreenKeyCode = "settings.hotkeyFullScreen.keyCode"
    static let hotkeyFullScreenModifiers = "settings.hotkeyFullScreen.modifiers"
    static let hotkeyWindowKeyCode = "settings.hotkeyWindow.keyCode"
    static let hotkeyWindowModifiers = "settings.hotkeyWindow.modifiers"
    static let hotkeyScrollingKeyCode = "settings.hotkeyScrolling.keyCode"
    static let hotkeyScrollingModifiers = "settings.hotkeyScrolling.modifiers"
}

enum SettingsStoreLegacyKeys {
    static let previewTimeoutSeconds = "settings.previewTimeoutSeconds"
    static let hotkeySelection = "settings.hotkeySelection"
    static let hotkeyFullScreen = "settings.hotkeyFullScreen"
    static let hotkeyWindow = "settings.hotkeyWindow"
}
